"use client";

import Link from "next/link";
import { useState, type CSSProperties } from "react";
import { ArrowDown, ArrowRight, BarChart3, Boxes, Check, ChevronRight, Clock3, GitBranch, Layers3, Play, Plus, Minus, SlidersHorizontal, Sparkles, Activity, CircleArrowOutUpRight, Hospital, Landmark, Utensils, Package, Headphones, MoveUpRight } from "lucide-react";
import styles from "./landing-page.module.css";

const nodes = [
  { type: "Source", name: "Incoming requests", detail: "Every 3 min · exponential", icon: Plus, color: "#79bd9a" },
  { type: "Queue", name: "Support queue", detail: "30 places · FIFO", icon: Layers3, color: "#e4b66a" },
  { type: "Process", name: "Agent service", detail: "4 min · exponential", icon: Boxes, color: "#f1846c" },
  { type: "Decision", name: "Resolved?", detail: "80% close · 20% follow-up", icon: GitBranch, color: "#c7b4de" },
  { type: "Delay", name: "Follow-up", detail: "2 min · constant", icon: Clock3, color: "#e4b66a" },
  { type: "Sink", name: "Request closed", detail: "Completed requests", icon: Check, color: "#79bd9a" },
];
const outcomes = {
  1: { completed: 112, wait: 37.6, queue: 14.8, utilization: 96, bars: [22, 41, 57, 71, 83, 91, 96, 100] },
  2: { completed: 149, wait: 3.8, queue: 1.3, utilization: 66, bars: [14, 27, 40, 53, 62, 77, 88, 100] },
  3: { completed: 155, wait: 0.7, queue: 0.2, utilization: 45, bars: [12, 25, 38, 51, 64, 76, 89, 100] },
  4: { completed: 156, wait: 0.2, queue: 0.1, utilization: 34, bars: [12, 24, 37, 50, 62, 75, 88, 100] },
};
type Resources = keyof typeof outcomes;
type View = "Model" | "Analytics" | "Scenarios";

function Brand() {
  return <span className={styles.brand}><svg viewBox="0 0 100 100" aria-hidden="true"><path fill="currentColor" d="M50 0C47 22 42 42 0 50C42 58 47 78 50 100C53 78 58 58 100 50C58 42 53 22 50 0Z" /><circle cx="50" cy="50" r="13" fill="#f8f7f3" /></svg>Astra<span className={styles.brandDot}>.</span></span>;
}
function GetStarted() {
  return <Link className={styles.cta} href="/register">Get started <ArrowRight size={17} aria-hidden="true" /></Link>;
}
function Demo() {
  const [view, setView] = useState<View>("Model");
  const [selected, setSelected] = useState(2);
  const [resources, setResources] = useState<Resources>(2);
  const [runResources, setRunResources] = useState<Resources | null>(null);
  const [scenario, setScenario] = useState<"baseline" | "changed">("changed");
  const [runs, setRuns] = useState(0);
  const result = outcomes[runResources ?? resources];
  const comparisonResources = resources === 2 ? 3 : resources;
  const compared = outcomes[scenario === "baseline" ? 2 : comparisonResources];
  function run() { setRunResources(resources); setRuns(runs + 1); setView("Analytics"); }
  return <div className={styles.demo} id="demo" aria-label="Interactive Astra sample simulator">
    <div className={styles.demoTop}><span className={styles.demoMark}><Sparkles size={16} aria-hidden="true" /> astra <span>/</span> <span>Customer service flow</span></span><span className={styles.demoBadge}><i /> Interactive demo</span></div>
    <div className={styles.toolbar}><div className={styles.tabs} aria-label="Demo views">{(["Model", "Analytics", "Scenarios"] as View[]).map((tab) => <button key={tab} aria-pressed={view === tab} onClick={() => setView(tab)} className={view === tab ? styles.activeTab : ""}>{tab === "Model" ? <GitBranch size={14} /> : tab === "Analytics" ? <BarChart3 size={14} /> : <Layers3 size={14} />}{tab}</button>)}</div><button className={styles.run} onClick={run}><Play size={12} fill="currentColor" aria-hidden="true" /> Run simulation</button></div>
    {view === "Model" && <div className={styles.modelView}>
      <div className={styles.canvas}><div className={styles.canvasCaption}><span>MODEL / 01</span><span>480 simulated minutes</span></div><div className={styles.flow}>
        <svg className={styles.connections} viewBox="0 0 660 330" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="demo-arrow" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0 6 3 0 6" fill="none" stroke="#77766f" /></marker></defs><g fill="none" stroke="#77766f" strokeWidth="1.3" markerEnd="url(#demo-arrow)"><path d="M180 85 H235"/><path d="M425 85 H475"/><path d="M565 125 V176 H95 V215"/><path d="M180 255 H235"/><path d="M425 255 H475"/><path d="M95 295 V320 H565 V295"/></g><text x="235" y="204" fill="#aba69d" fontSize="10">20% follow-up</text><text x="285" y="314" fill="#aba69d" fontSize="10">80% close directly</text></svg>
        {nodes.map((node, index) => <button key={node.type} className={`${styles.node} ${selected === index ? styles.selectedNode : ""}`} style={{ "--node-color": node.color } as CSSProperties} onClick={() => setSelected(index)} aria-pressed={selected === index} aria-label={`Select ${node.type}: ${node.name}`}><span className={styles.nodeType}><node.icon size={14} aria-hidden="true" />{node.type}</span><strong>{node.name}</strong><small>{index === 2 ? `${resources} agents · 4 min avg` : node.detail}</small><span className={styles.portIn} /><span className={styles.portOut} /></button>)}
      </div><div className={styles.canvasFooter}><span><i /> Connected process flow</span><span>Select a node to inspect it</span></div></div>
      <aside className={styles.inspector}><span className={styles.microLabel}>NODE PROPERTIES</span><div className={styles.inspectorTitle}><SlidersHorizontal size={17} aria-hidden="true" /><strong>{nodes[selected].name}</strong></div><p>{["Requests enter the process on an exponential arrival schedule.", "Requests wait in arrival order until an agent is available.", "Agents serve requests. Try adding a resource to see how the queue changes.", "Requests split into two routes: 80% close directly, 20% need follow-up.", "Follow-up adds a fixed delay of 2 minutes, without using an agent.", "Completed requests leave the process and contribute to throughput."][selected]}</p>{selected === 2 ? <><label className={styles.fieldLabel}>Resources <span>agents</span></label><div className={styles.stepper}><button aria-label="Remove one agent" disabled={resources === 1} onClick={() => setResources((resources - 1) as Resources)}><Minus size={15} /></button><output aria-live="polite">{resources}</output><button aria-label="Add one agent" disabled={resources === 4} onClick={() => setResources((resources + 1) as Resources)}><Plus size={15} /></button></div><div className={styles.propertyRow}><span>Service time</span><strong>4 min avg</strong></div><div className={styles.propertyRow}><span>Distribution</span><strong>Exponential</strong></div></> : <div className={styles.propertyRow}><span>{nodes[selected].type}</span><strong>{nodes[selected].detail}</strong></div>}<div className={styles.demoTip}><span>TRY A WHAT-IF</span><p>Select Agent service, change the number of agents, then run the sample.</p></div></aside>
    </div>}
    {view === "Analytics" && <div className={styles.analytics}><div className={styles.panelHeading}><div><span className={styles.microLabel}>SIMULATION SUMMARY</span><h3>{runResources === null ? "Preview the possibilities." : "A clearer picture of your operation."}</h3></div><span className={styles.resultBadge}>{runResources ?? resources} agents · 8 hours</span></div><div className={styles.metrics}>{[[String(result.completed), "Requests completed"], [`${result.wait} min`, "Average wait time"], [String(result.queue), "Average queue length"], [`${result.utilization}%`, "Agent utilization"]].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className={styles.chartRow}><div className={styles.chart}><div><strong>Cumulative completions</strong><span>sample / 8 hours</span></div><div className={styles.bars} role="img" aria-label={`Illustrative cumulative completions rise over eight hours to ${result.completed} requests`}>{result.bars.map((height, i) => <div key={i}><i style={{ height: `${height}%` }} /><span>{i + 1}h</span></div>)}</div></div><div className={styles.insight}><Activity size={20} aria-hidden="true" /><span>BOTTLENECK EVIDENCE</span><h4>{result.utilization > 90 ? "Agent capacity is under pressure." : "The queue tells the story."}</h4><p>{result.utilization > 90 ? "High utilization and a growing queue suggest agent service is limiting throughput in this sample." : `With ${runResources ?? resources} agents, requests wait ${result.wait} minutes on average. Compare scenarios to see the resource tradeoff.`}</p><button onClick={() => setView("Scenarios")}>Compare scenarios <ArrowRight size={14} /></button></div></div></div>}
    {view === "Scenarios" && <div className={styles.analytics}><div className={styles.panelHeading}><div><span className={styles.microLabel}>SCENARIO COMPARISON</span><h3>One change. See the difference.</h3></div><span className={styles.resultBadge}>Illustrative outcomes</span></div><div className={styles.scenarioButtons}><button aria-pressed={scenario === "baseline"} className={scenario === "baseline" ? styles.chosenScenario : ""} onClick={() => setScenario("baseline")}><Layers3 size={16} /><span><strong>Baseline</strong><small>2 service agents</small></span>{scenario === "baseline" && <Check size={16} />}</button><button aria-pressed={scenario === "changed"} className={scenario === "changed" ? styles.chosenScenario : ""} onClick={() => setScenario("changed")}><SlidersHorizontal size={16} /><span><strong>Changed configuration</strong><small>{comparisonResources} service agents</small></span>{scenario === "changed" && <Check size={16} />}</button></div><div className={styles.compareTable} role="table" aria-label="Illustrative scenario outcomes"><div role="row"><span role="columnheader">8-hour sample</span><span role="columnheader">Baseline · 2 agents</span><span role="columnheader">Selected · {scenario === "baseline" ? 2 : comparisonResources} agents</span></div>{[["Completed", "149", String(compared.completed)], ["Average wait", "3.8 min", `${compared.wait} min`], ["Average queue", "1.3", String(compared.queue)], ["Utilization", "66%", `${compared.utilization}%`]].map(([label, baseline, value]) => <div key={label} role="row"><strong role="rowheader">{label}</strong><span role="cell">{baseline}</span><span role="cell">{value}</span></div>)}</div><p className={styles.scenarioNote}>More resources can reduce waiting, but may lower utilization. Explore the tradeoff before changing your operation.</p></div>}
    <div className={styles.demoBottom}><span>Illustrative sample data · runs locally in your browser</span><span role="status" aria-live="polite">{runs ? `Sample run ${runs} complete · ${runResources} agents` : "Ready to explore"}</span></div>
  </div>;
}
const capabilities = [
  { icon: GitBranch, title: "Think in process flows.", text: "Connect sources, queues, processes, decisions, delays, and sinks in a visual model." },
  { icon: Play, title: "Give your what-ifs a run.", text: "Adjust resources and timing. Run a simulation to see how your operation responds." },
  { icon: BarChart3, title: "Make the numbers clear.", text: "Explore throughput, wait time, queue length, and resource utilization together." },
  { icon: Layers3, title: "Compare before you change.", text: "Compare scenarios side by side and understand the tradeoffs in each configuration." },
  { icon: Activity, title: "Find where the flow slows.", text: "Review bottleneck evidence from queues and resource demand to guide your next change." },
];
const useCases = [
  { icon: Hospital, name: "Hospital", text: "From registration to discharge. Explore patient queues and doctor capacity.", tags: "Patient flow / Staff utilization" },
  { icon: Landmark, name: "Bank", text: "Balance waiting-area capacity and service counters against customer arrivals.", tags: "Service queues / Wait time" },
  { icon: Utensils, name: "Restaurant", text: "Follow an order from cashier to kitchen to pickup, and locate the slowest stage.", tags: "Order flow / Kitchen capacity" },
  { icon: Package, name: "Warehouse", text: "Model picking, packing, and dispatch to understand how work moves through the floor.", tags: "Fulfillment / Throughput" },
  { icon: Headphones, name: "Customer-service center", text: "Explore agent capacity, support queues, and specialist escalation paths.", tags: "Support flow / Resource use" },
];
export function LandingPage() {
  return <div className={styles.page}><a className={styles.skip} href="#main-content">Skip to content</a><header className={styles.header}><a href="#" aria-label="Astra home"><Brand /></a><nav aria-label="Main navigation"><a href="#capabilities">Product</a><a href="#how-it-works">How it works</a><a href="#use-cases">Use cases</a></nav><span className={styles.headerNote}><i /> Built for better decisions</span></header><main id="main-content"><section className={styles.hero}><div className={styles.eyebrow}><span /> VISUAL DISCRETE EVENT SIMULATION</div><h1>Understand the flow.<br />Improve <em>what comes next.</em></h1><p className={styles.heroCopy}>Build a process flow. Test your what-ifs. See how every change affects<br className={styles.desktopBreak} /> queues, throughput, wait times, and resource use.</p><GetStarted /><p className={styles.heroNote}>Your operation, with room to experiment.</p><div className={styles.demoIntro}><span><i /> A little model. A lot to learn.</span><span>Try it for yourself <ArrowDown size={14} /></span></div><Demo /><div className={styles.demoUnder}><span>MODEL IT. TEST IT. UNDERSTAND IT.</span><p>A safe place to explore changes before making them in the real world.</p></div></section>
    <section className={styles.capabilities} id="capabilities"><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>FROM COMPLEXITY TO CLARITY</span><h2>See your operation.<br /><em>Find your next move.</em></h2></div><p>Bring the flow, the numbers, and the tradeoffs into one workspace. Turn operational questions into models you can explore.</p></div><div className={styles.capabilityGrid}>{capabilities.map(({ icon: Icon, title, text }, i) => <article key={title}><div className={styles.cardTop}><Icon size={23} strokeWidth={1.5} aria-hidden="true" /><span>0{i + 1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.how} id="how-it-works"><span className={styles.eyebrow}>HOW ASTRA WORKS</span><h2>From “what if” to <em>“now we know.”</em></h2><div className={styles.steps}>{[{ title: "Build your model", text: "Map how people, orders, or requests move. Define arrivals, queues, service times, and resources.", icon: GitBranch }, { title: "Run a simulation", text: "Set the simulation duration, change a parameter, and explore how the process behaves over time.", icon: Play }, { title: "Make an informed change", text: "Inspect analytics, compare scenarios, and use bottleneck evidence to decide what to try next.", icon: CircleArrowOutUpRight }].map(({ title, text, icon: Icon }, i) => <article key={title}><div className={styles.stepVisual}><span>0{i + 1}</span><Icon size={35} strokeWidth={1.2} aria-hidden="true" />{i < 2 && <ChevronRight className={styles.stepArrow} size={21} aria-hidden="true" />}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.useCases} id="use-cases"><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>REAL PROCESSES. EXPLORABLE POSSIBILITIES.</span><h2>Different operations.<br /><em>The same useful questions.</em></h2></div><p>Start with one of Astra’s editable templates, then shape the model around your process. These are starting points, not customer stories.</p></div><div className={styles.useGrid}>{useCases.map(({ icon: Icon, name, text, tags }) => <article key={name}><Icon size={26} strokeWidth={1.5} aria-hidden="true" /><h3>{name}</h3><p>{text}</p><span>{tags}</span></article>)}<div className={styles.useClosing}><GitBranch size={36} strokeWidth={1.3} aria-hidden="true" /><h3>Or start with<br /><em>your own flow.</em></h3><p>A blank canvas for the operation you know best.</p></div></div></section>
    <section className={styles.finalCta}><span className={styles.eyebrow}>MAKE SPACE FOR BETTER WHAT-IFS</span><h2>Your next improvement<br />starts with <em>understanding.</em></h2><p>Bring your process to Astra. See what could work better.</p><GetStarted /><span className={styles.ctaDecoration} aria-hidden="true">✳</span></section></main><footer className={styles.footer}><a href="#" aria-label="Astra home"><Brand /></a><p>Model. Simulate. Improve.</p><nav aria-label="Footer navigation"><a href="#capabilities">Product</a><a href="#demo">Interactive demo <MoveUpRight size={11} aria-hidden="true" /></a><a href="#use-cases">Use cases</a></nav><span>© {new Date().getFullYear()} Astra</span></footer></div>;
}
